### ISSUE TITLE
How do I run?

### ISSUE THREAD

**Issue by vinibispo** [emacs-grammarly/grammarly-language-server#5]
I'm trying to set up this language server on neovim, but it's not clear enough how I run this server.
And which versions of NodeJS and pnpm are required.
Could you explain me?

**Comment by jcs090218** [comment]
Hmm... isn't neovim using the upstream language server (`@znck/grammarly`)?

You should probably check the document in neovim's repo https://github.com/neovim/nvim-lspconfig/blob/master/doc/server_configurations.md#grammarly. Would this be sufficient?

**Comment by vinibispo** [comment]
For sure, thanks
